service: playtube-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    PORT: ${env:PORT}
    CORS_ORIGIN: ${env:CORS_ORIGIN}
    MONGODB_URI: ${env:MONGODB_URI}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    ACCESS_TOKEN_EXPIRY: ${env:ACCESS_TOKEN_EXPIRY}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}
    REFRESH_TOKEN_EXPIRY: ${env:REFRESH_TOKEN_EXPIRY}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    CLOUDINARY_URL: ${env:CLOUDINARY_URL}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-dotenv-plugin
